# ByteDance Volcengine EMR, Copyright 2024.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The module contains version information about the tosfs package."""

#
# Generated by scripts/generate_version.sh
#
class Version:
    """The version information about the tosfs package."""
    version = "2026.3.1"
    revision = "57682ca3e0a8ef04ba711283d8e3bb7c925893bc"
    user = "bytedance"
    date = "Fri Mar 27 14:57:12 CST 2026"
    repo_url = "https://github.com/fsspec/tosfs.git"
